CREATE DATABASE IF NOT EXISTS telegembot;
USE telegembot;

CREATE USER IF NOT EXISTS 'botuser'@'%' IDENTIFIED BY '${MYSQL_BOTUSER_PASSWORD}';
GRANT ALL PRIVILEGES ON telegembot.* TO 'botuser'@'%';
FLUSH PRIVILEGES;
